version: '3'
services:
  react-app:
    image: react-app
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - "app-network"
  api-server:
    image: api-server
    ports:
      - "5000:5000"
    networks:
      - "app-network"
networks:
  app-network:
    driver: bridge
  